### ISSUE TITLE
Huuuge class

### ISSUE THREAD

**Issue by IliaIlin** [SH-Files/First-Project#3]
https://github.com/SH-Files/First-Project/blob/f95bc05c308a5d9ecd2c8a0d1ae4327f68f200e0/src/Main.java#L660

Although the naming and structure are quite good, this class is doing too many things. Extract this logic into a set of readable classes with a clear purpose

**Comment by SH-Files** [comment]
Not quilte sure how to split this class. Should I transform the TreeMaps into classes?

**Comment by SH-Files** [comment]
Not quite sure how I should split this class. Can you give me a hint?
